NumPlots : "5"
KSize : "32"
Buffer : "4000"
Threads : "2"
Buckets : "128"
TempPath : "/home"
Total : 3
Sleep : 0
RunPath : "/home/test"
FinalPath :
  - "/home/test1"
  - "/home/test2"
  - "/home/test3"