NumPlots : "5"
KSize : "32"
Buffer : "4000"
Threads : "2"
Buckets : "128"
TempPath : "/home/sun/Works/go/src/ChiaAutoPlotsing/test"
Total : 1
Sleep : 0
RunPath : "/home/sun/Works/go/src/ChiaAutoPlotsing/test"
FinalPath :
  - "/home/sun/Works/go/src/ChiaAutoPlotsing/test"
  - "/home/sun/Works/go/src/ChiaAutoPlotsing/test"